### PR TITLE
Added a capability to post install packages when being installed via a workspace

### PR DESCRIPTION
**Pull request by timjroberts**
If a packages' package.json contains a 'npm-workspace:install' script, then
it will be executed by npm-workspace when the package has been installed.
This allows packages to execute install scripts that execute only when the
package is installed via npm-workspace.

### CODE REVIEW

**Comment by mariocasciaro** [comment]
Hi Tim, this is a nice idea, the code looks good too. Could you just add a note in the README so other users know of the new feature? Thanks!

**Comment by timjroberts** [comment]
README updated...

**Comment by mariocasciaro** [comment]
Cheers!

**Comment by timjroberts** [comment]
Hi Mario - this hasn't made it into a release yet. NPM is reporting v0.5.0.

**Comment by mariocasciaro** [comment]
Hey Tim, sorry, version 0.6.0 is now on npm.

**Pull request merged**
